### ISSUE TITLE
Update tag line from check how well you are doing in hacktober to open source immersion alternative

### ISSUE THREAD

**Issue by prondubuisi** [prondubuisi/pr-checker#5]

**Comment by stephenjude** [comment]
Looks like this issue has been fixed by these PRs
#7 #8

**Comment by prondubuisi** [comment]
Nice Catch @stephenjude, this has been partially fulfilled  but we still have some instances of hacktober in the codebase 
![Hacktober Change](https://user-images.githubusercontent.com/22311928/89196122-abfa9b00-d5a1-11ea-9d51-a13e877fcc6e.png)

**Comment by stephenjude** [comment]
Oh, just found out. Let me work on it.

**Comment by prondubuisi** [comment]
Fixed with #10
